#!/bin/bash

cd "$(dirname "$0")"/.. || exit

echo "Linting hume..."
# shellcheck disable=SC2046
flake8 $(find . -name "*.py")

coverage run --source hume -m unittest discover -s tests -f
coverage report -m --fail-under 96
